import {
  FileText,
  Receipt,
  Building2,
  FileSpreadsheet,
  ClipboardCheck,
  Rocket,
  ShieldCheck,
  ListChecks,
  ScanEye,
  MessageCircle,
  FileCheck2,
  Briefcase,
  Users,
  Store,
  Landmark,
  AlertCircle,
  HelpCircle,
  IndianRupee,
  Clock,
  Phone,
  Mail,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/content/types";

// Maps content icon keys to lucide-react components. One icon family only.
export const iconMap: Record<IconKey, LucideIcon> = {
  fileText: FileText,
  receipt: Receipt,
  building: Building2,
  spreadsheet: FileSpreadsheet,
  clipboardCheck: ClipboardCheck,
  rocket: Rocket,
  shieldCheck: ShieldCheck,
  listChecks: ListChecks,
  scanEye: ScanEye,
  messageCircle: MessageCircle,
  fileCheck: FileCheck2,
  briefcase: Briefcase,
  users: Users,
  store: Store,
  landmark: Landmark,
  alertCircle: AlertCircle,
  helpCircle: HelpCircle,
  rupee: IndianRupee,
  clock: Clock,
  phone: Phone,
  mail: Mail,
};
